export const projectData = [
    {
        id:1,
        name:"Personal Website",
        description: "Built a website with React.js, and automated the deployment process with git and Netlify (as you can tell from the domain).",
        link:"https://tiffanylaw.netlify.com/",
        img:"./img/webapp.jpeg",
        date:"Nov 2019",
        language: "CSS, HTML, ES6",
        lib: "React",
        tools: "Git, Netlify",
    },
    {
        id:2,
        name:"Final Year Project",
        description: "",
        link:"https://github.com/lawheitung/hkia_fyp",
        img:"./img/datamining.jpg",
        date:"Dec 2018",
        language: "Python",
        lib: "Scrappy, ipynb",
        tools: " – ",
    },
    {
        id:3,
        name:"CONVID-19 Hackathon – Netic Health",
        description: "Build the website with React.js, and automate the deployment process with git and Netlify (as you can tell from the domain).",
        link:"https://devpost.com/software/netic-health",
        img:"./img/hackathon.jpeg",
        date:"Mar 2020",
        language: "Global Team",
        lib: "Tele-rehab",
        tools: "Squarespace, GoogleSuite",
    },
    {
        id:4,
        name:"Data Science Capstone Project @ IBM/Coursera (On-going)",
        link:"https://github.com/lawheitung/AppliedDataScienceCapstone",
        img:"./img/AIML.jpeg",
        date:"Feb 2020",
        language: "Python",
        lib: "Folium, pandas, numpy",
        tools: "Git, ipynb, Foursquare API",
    },
    // {
    //     id:5,
    //     name:"Data Science Capstone Project @ IBM/Coursera (On-going)",
    //     link:"https://github.com/lawheitung/AppliedDataScienceCapstone",
    //     date:"Apr 2020",
    //     language: "Python",
    //     lib: "Folium, pandas, numpy",
    //     tools: "Git, ipynb, Foursquare API",
    // }
]